### PR TITLE
Requirements separation

### LINKED ISSUE #7: requirement subprocess error when installing via pip
I cloned the repo & run `pip install -e .`

Here is my terminal output:

```
alex-macbook:~/Desktop/bids_neuropoly $ pip install -e .
Obtaining file:///Users/alfoi/Desktop/bids_neuropoly
Requirement already satisfied: pybids>=0.6.5 in /Users/alfoi/anaconda2/lib/python2.7/site-packages (from bids-neuropoly==0.1) (0.6.5)
Requirement already satisfied: nibabel>=2.3.0 in /Users/alfoi/anaconda2/lib/python2.7/site-packages (from bids-neuropoly==0.1) (2.3.0)
Requirement already satisfied: pandas>=0.23.0 in /Users/alfoi/anaconda2/lib/python2.7/site-packages (from bids-neuropoly==0.1) (0.23.0)
Requirement already satisfied: gitpython in /Users/alfoi/anaconda2/lib/python2.7/site-packages (from bids-neuropoly==0.1) (2.1.11)
Collecting logging (from bids-neuropoly==0.1)
  Downloading https://files.pythonhosted.org/packages/93/4b/979db9e44be09f71e85c9c8cfc42f258adfb7d93ce01deed2788b2948919/logging-0.4.9.6.tar.gz (96kB)
    100% |████████████████████████████████| 102kB 3.8MB/s 
Collecting subprocess (from bids-neuropoly==0.1)
  Could not find a version that satisfies the requirement subprocess (from bids-neuropoly==0.1) (from versions: )
No matching distribution found for subprocess (from bids-neuropoly==0.1)
You are using pip version 18.1, however version 19.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

### PR DESCRIPTION
**Pull request by alexfoias**
The aim of this PR is to split the API & script (convert_dcm2nii) requirements.

To install the  **convert_dcm2nii** script run:  `pip install -r scripts/requirements.txt`

Fixes #7

### CODE REVIEW

**Comment by alexfoias** [comment]
I will update the readme file soon.

**Comment by jcohenadad** [comment]
i'll review when everything is finalized (incl. readme)

**Comment by perone** [comment]
I need this change to finish the package before uploading to PyPI repository, so I'll be able to depend on it on the ivado project, can we merge this PR and add the readme later ?

**Review by perone — APPROVED** [review]

**Comment by alexfoias** [comment]
@perone I will do it in 2 min.

**Comment by alexfoias** [comment]
@perone @jcohenadad I updated the readme

**Review by jcohenadad — APPROVED** [review]
good-- at some point maybe we should just move the conversion script directly inside the spine_generic repos...

**Pull request merged**
