### PR TITLE
Create publish_package.yml

### PR DESCRIPTION
**Pull request by olix86**
Add script for uploading package to pipy when a release is created

### CODE REVIEW

**Review by jcohenadad — APPROVED** [review]

**Comment by olix86** [comment]
@jcohenadad @alexfoias I don't have write access to this repo so somebody else would have to merge the PR

**Comment by jcohenadad** [comment]
@olix86 just gave you the rights for the future

**Comment by alexfoias** [comment]
@olix86 I added the secret to the GH for pypi. Do I need to do something else ?

@jcohenadad I think we have to do a new release. @olix86 Could you please do it after we got the okay ?

**Comment by olix86** [comment]
>  I added the secret to the GH for pypi. Do I need to do something else ?

Yep that should work assuming Christian has given us the rights to the packages on pipy

**Comment by alexfoias** [comment]
Yes, neuropoly has ownership to the pypi package and the token was associated for https://pypi.org/project/bids-neuropoly/

**Pull request merged**
