### PR TITLE
fixes gre-t1w being exported as t1w

### PR DESCRIPTION
**Pull request by alexfoias**
Fixes https://github.com/neuropoly/bids_neuropoly/issues/2

### CODE REVIEW

**Review by jcohenadad — CHANGES_REQUESTED** [review]
no, this fix will break with the Philips scans (which are named GRE-T1), we need to find another solution

**Comment by alexfoias** [comment]
would it work if we keep 'GRE-T1': ('acq-T1w_MTS', 'anat') and add a new entry 'GRE-T1w': ('acq-T1w_MTS', 'anat') ?

**Comment by jcohenadad** [comment]
> would it work if we keep 'GRE-T1': ('acq-T1w_MTS', 'anat') and add a new entry 'GRE-T1w': ('acq-T1w_MTS', 'anat') ?

yes good idea, i think that could work. Please comment in from of the 'GRE-T1': ('acq-T1w_MTS', 'anat') line, that this is a hack for Philips protocols

**Comment by alexfoias** [comment]
I added the comment and pushed in my branch. Is there a way to do a PR rebase  or should I open a new PR ?

**Review by jcohenadad — COMMENTED** [review]
what will happen in the Siemens case, is that the same file will be copied twice-- so just make sure that this does not raise an error (i.e., overwriting allowed?)

**Comment by alexfoias** [comment]
I tried it on a Siemens dataset & it works, here is what I have:
Detected: /var/folders/_8/wq4mlll97hn7w0hw84bs4stw0000gn/T/tmp4N69vs/sct_037_GRE-T1w_20190111130730_7.nii.gz --> GRE-T1w
Detected: /var/folders/_8/wq4mlll97hn7w0hw84bs4stw0000gn/T/tmp4N69vs/sct_037_T1w_20190111130730_2.nii.gz --> T1w

I don't have a Philips dataset to test it.

**Review by jcohenadad — APPROVED** [review]

**Pull request merged**
